### ISSUE TITLE
Core: introduce recommendation units with automatic event tracking

### ISSUE THREAD

**Issue by simonpai** [MisoAI/miso-client-js-sdk#62]
* [x] Plugin: `std:units`
  * [x] `items.scan()` and tracker options: `autoScan` (default true)
  * [x] `items.watch()`
  * [x] tracker options: `click.lenient` (default true)
  * [x] ~preprocess payload~ (make this general)
* [x] Demo
  * [x] Basic
  * [x] Resync
  * [x] Watch
* [x] Docs

**Comment by simonpai** [comment]
Clean up and write more docs before we close this.
